INSERT INTO channel_notification (textChannelID,
                                  guildID,
                                  roleID,
                                  message,
                                  headUp,
                                  ancientarena,
                                  ancientnightmare,
                                  assembly,
                                  battlegrounds,
                                  vault,
                                  demongates,
                                  shadowlottery,
                                  hauntedcarriage,
                                  demongatesembed,
                                  ancientarenaembed,
                                  hauntedcarriageembed,
                                  ancientnightmareembed,
                                  wrathborneinvasion,
                                  tower_of_victory_enabled,
                                  shadow_war_enabled)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)